DROP TABLE IF EXISTS GENRES;

CREATE TABLE GENRES
(
    ID   BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE AUTHORS
(
    ID        BIGINT IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR(300) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS
(
    ID        BIGINT IDENTITY PRIMARY KEY,
    TITLE     VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT       NOT NULL,
    GENRE_ID  BIGINT       NOT NULL,
    CONSTRAINT AUTHOR_ID_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
    CONSTRAINT GENRE_ID_FL FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID)
);

DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS
(
    ID      BIGINT IDENTITY PRIMARY KEY,
    TEXT    VARCHAR(1000) NOT NULL,
    BOOK_ID BIGINT        NOT NULL REFERENCES BOOKS (ID) ON DELETE CASCADE

);

CREATE TABLE USERS (
    ID          BIGINT IDENTITY PRIMARY KEY,
    NAME        VARCHAR(255),
    PASSWORD    VARCHAR(255),
    AUTHORITY   VARCHAR(255)
);
