spring:
  application:
    name: online-library-genre-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres

server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8001/eureka}
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    instance-id: ${spring:application:name}:${server:port}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
