spring:
  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
#    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres
    initialization-mode: always
    data: classpath*:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    ROOT: DEBUG
