DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS
(
    ID        BIGINT IDENTITY PRIMARY KEY,
    TITLE     VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT       NOT NULL,
    GENRE_ID  BIGINT       NOT NULL
);
